# -*- coding: utf-8 -*-
"""FINAL FINAL OMR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nMbhqtLB6vWPVSSr5NavTTpoj38aqxaM
"""

# omr_hybrid_full.py

import os
import cv2
import json
import numpy as np
from typing import List, Tuple, Dict

import matplotlib.pyplot as plt

import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.optimizers import Adam

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    confusion_matrix,
    ConfusionMatrixDisplay,
    roc_curve,
    auc,
    classification_report,
)
from sklearn.preprocessing import label_binarize


# ----------------------------- Bubble CNN -----------------------------

class BubbleClassifierCNN:
    """
    CNN model for classifying bubble markings (Marked vs Unmarked)
    """
    def __init__(self, input_size=(32, 32, 1)):
        self.input_size = input_size
        self.model = None
        self.history = None
        self.last_val = None
        # --- Added: store test set + per-epoch test metrics ---
        self.last_test = None
        self.test_metrics = {"loss": [], "accuracy": []}
        # ------------------------------------------------------
        self.build_model()

    def build_model(self):
        """Build a compact CNN for bubble classification"""
        self.model = models.Sequential([
            layers.Conv2D(32, (3, 3), activation='relu', input_shape=self.input_size),
            layers.MaxPooling2D((2, 2)),

            layers.Conv2D(64, (3, 3), activation='relu'),
            layers.MaxPooling2D((2, 2)),

            layers.Conv2D(64, (3, 3), activation='relu'),

            layers.Flatten(),
            layers.Dense(64, activation='relu'),
            layers.Dropout(0.5),
            layers.Dense(1, activation='sigmoid')  # Binary output
        ])
        self.model.compile(optimizer=Adam(learning_rate=0.001),
                           loss='binary_crossentropy',
                           metrics=['accuracy'])

    def preprocess_bubble_image(self, bubble_img: np.ndarray) -> np.ndarray:
        """Resize to 32x32x1, normalize to [0,1], add batch dim"""
        if bubble_img.ndim == 3:
            bubble_img = cv2.cvtColor(bubble_img, cv2.COLOR_BGR2GRAY)
        resized = cv2.resize(bubble_img, self.input_size[:2])
        normalized = resized.astype('float32') / 255.0
        normalized = normalized.reshape(self.input_size)  # (H,W,1)
        return np.expand_dims(normalized, axis=0)  # (1,H,W,1)

    def predict_marking(self, bubble_img: np.ndarray) -> Tuple[bool, float]:
        """Predict if bubble is marked (True/False) and confidence"""
        processed_img = self.preprocess_bubble_image(bubble_img)
        prediction = float(self.model.predict(processed_img, verbose=0)[0][0])
        is_marked = prediction > 0.5
        confidence = prediction if is_marked else (1.0 - prediction)
        return is_marked, confidence

    def generate_synthetic_training_data(self, num_samples=2000, seed=42):
        """Generate synthetic circles (marked/unmarked) for quick training"""
        X, y = [], []
        rng = np.random.default_rng(seed)

        for _ in range(num_samples):
            img = np.ones((32, 32), dtype=np.uint8) * 255
            cv2.circle(img, (16, 16), 12, 0, 2)

            is_marked = bool(rng.integers(0, 2))
            if is_marked:
                fill_intensity = int(rng.integers(50, 150))
                cv2.circle(img, (16, 16), 10, fill_intensity, -1)
                y.append(1)
            else:
                noise = rng.normal(0, 10, img.shape)
                img = np.clip(img + noise, 0, 255)
                y.append(0)

            noise = rng.normal(0, 5, img.shape)
            img = np.clip(img + noise, 0, 255).astype(np.uint8)
            X.append(img)

        X = np.array(X).reshape(-1, 32, 32, 1) / 255.0
        y = np.array(y, dtype=np.float32)
        return X, y

    def train_model(self, epochs=10, validation_split=0.2):
        """Train CNN on synthetic data and store history + validation set"""
        print("Generating synthetic training data...")
        X, y = self.generate_synthetic_training_data(2000)

        X_train, X_val, y_train, y_val = train_test_split(
            X, y, test_size=validation_split, random_state=42, stratify=y
        )

        # --- Added: create a separate synthetic TEST set ---
        X_test, y_test = self.generate_synthetic_training_data(800, seed=999)
        self.last_test = (X_test, y_test)
        # ---------------------------------------------------

        print("Training CNN model...")

        # --- Added: Keras callback to log TEST loss/accuracy per epoch ---
        class TestMetricsCallback(tf.keras.callbacks.Callback):
            def __init__(self, model_ref, X_t, y_t, sink_dict):
                super().__init__()
                self.model_ref = model_ref
                self.X_t = X_t
                self.y_t = y_t
                self.sink = sink_dict

            def on_epoch_end(self, epoch, logs=None):
                loss, acc = self.model_ref.evaluate(self.X_t, self.y_t, verbose=0)
                self.sink["loss"].append(loss)
                self.sink["accuracy"].append(acc)
                # Optional, quiet print:
                print(f"[Epoch {epoch+1}] test_loss={loss:.4f} test_acc={acc:.4f}")
        # ----------------------------------------------------------------

        history = self.model.fit(
            X_train, y_train,
            epochs=epochs,
            validation_data=(X_val, y_val),
            batch_size=32,
            verbose=1,
            callbacks=[TestMetricsCallback(self.model, X_test, y_test, self.test_metrics)]
        )

        self.history = history
        self.last_val = (X_val, y_val)
        return history

    def save_model(self, filepath="bubble_classifier.h5"):
        self.model.save(filepath)
        print(f"Model saved as {filepath}")

    def load_model(self, filepath="bubble_classifier.h5"):
        if os.path.exists(filepath):
            self.model = tf.keras.models.load_model(filepath)
            print(f"Model loaded from {filepath}")
            return True
        return False

    # ----------------- Plotting helpers (CNN) -----------------

    def plot_training_curves(self, save_prefix="cnn_training"):
        """Plot & save training/validation accuracy and loss curves"""
        if not self.history:
            print("No training history available to plot.")
            return
        h = self.history.history

        # Accuracy (train, val, test)
        plt.figure()
        plt.plot(h.get("accuracy", []), label="train")
        plt.plot(h.get("val_accuracy", []), label="val")
        # --- Added: test curve ---
        if self.test_metrics["accuracy"]:
            plt.plot(self.test_metrics["accuracy"], label="test")
        # -------------------------
        plt.title("CNN Accuracy")
        plt.xlabel("Epoch")
        plt.ylabel("Accuracy")
        plt.legend()
        plt.tight_layout()
        plt.savefig(f"{save_prefix}_accuracy.png", dpi=200)

        # Loss (train, val, test)
        plt.figure()
        plt.plot(h.get("loss", []), label="train")
        plt.plot(h.get("val_loss", []), label="val")
        # --- Added: test curve ---
        if self.test_metrics["loss"]:
            plt.plot(self.test_metrics["loss"], label="test")
        # -------------------------
        plt.title("CNN Loss")
        plt.xlabel("Epoch")
        plt.ylabel("Loss")
        plt.legend()
        plt.tight_layout()
        plt.savefig(f"{save_prefix}_loss.png", dpi=200)

    def plot_cnn_confusion_roc_auc(self, normalize="true", save_prefix="cnn_eval"):
        """
        Plot confusion matrix, ROC curve, and report AUC for CNN on validation data.
        If validation data not present (loaded a pre-trained model), evaluates on fresh synthetic split.
        """
        if not self.last_val:
            print("No validation data cached; generating synthetic validation for evaluation.")
            X, y = self.generate_synthetic_training_data(1000, seed=123)
            _, X_val, _, y_val = train_test_split(X, y, test_size=0.25, random_state=123, stratify=y)
        else:
            X_val, y_val = self.last_val

        y_val = y_val.astype(int)
        y_prob = self.model.predict(X_val, verbose=0).ravel()
        y_pred = (y_prob > 0.5).astype(int)

        # Confusion Matrix
        cm = confusion_matrix(y_val, y_pred, labels=[0, 1],
                              normalize=normalize if normalize else None)
        fig, ax = plt.subplots()
        disp = ConfusionMatrixDisplay(cm, display_labels=["Unmarked", "Marked"])
        disp.plot(ax=ax, values_format=".2f" if normalize else "d", colorbar=False)
        ax.set_title("CNN Confusion Matrix" + (" (normalized)" if normalize else ""))
        plt.tight_layout()
        plt.savefig(f"{save_prefix}_cm.png", dpi=200)

        # ROC & AUC
        fpr, tpr, _ = roc_curve(y_val, y_prob)
        roc_auc = auc(fpr, tpr)
        plt.figure()
        plt.plot(fpr, tpr, label=f"AUC = {roc_auc:.3f}")
        plt.plot([0, 1], [0, 1], "--")
        plt.xlabel("False Positive Rate")
        plt.ylabel("True Positive Rate")
        plt.title("CNN ROC Curve")
        plt.legend(loc="lower right")
        plt.tight_layout()
        plt.savefig(f"{save_prefix}_roc.png", dpi=200)

        print(f"\nCNN AUC: {roc_auc:.4f}")
        print("\nClassification report (binary):")
        print(classification_report(y_val, y_pred, target_names=["Unmarked", "Marked"]))


# ----------------------------- OMR Detector -----------------------------

class OMRDetector:
    def __init__(self, use_cnn=True, hybrid_mode=True):
        self.marking_threshold = 0.30
        self.use_cnn = use_cnn
        self.hybrid_mode = hybrid_mode
        self.cnn_model = None

        if use_cnn:
            self.cnn_model = BubbleClassifierCNN()
            # Load if exists; otherwise train quickly on synthetic data
            if not self.cnn_model.load_model():
                print("No pre-trained model found. Training new CNN model...")
                self.cnn_model.train_model(epochs=10)
                self.cnn_model.save_model()

    # ----------------- PREPROCESS & DETECTION -----------------

    def preprocess_image(self, image_path: str) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
        img = cv2.imread(image_path)
        if img is None:
            raise ValueError(f"Could not read image from {image_path}")
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        blurred = cv2.GaussianBlur(gray, (3, 3), 0)
        thresh = cv2.adaptiveThreshold(
            blurred, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY_INV, 15, 3
        )
        kernel = np.ones((2, 2), np.uint8)
        thresh = cv2.morphologyEx(thresh, cv2.MORPH_OPEN, kernel)
        thresh = cv2.morphologyEx(thresh, cv2.MORPH_CLOSE, kernel)
        return img, gray, thresh

    def find_circles(self, gray: np.ndarray) -> List[Tuple[int, int, int]]:
        circles = cv2.HoughCircles(
            gray,
            cv2.HOUGH_GRADIENT,
            dp=1,
            minDist=25,
            param1=50,
            param2=35,
            minRadius=10,
            maxRadius=30
        )
        if circles is not None:
            circles = np.round(circles[0, :]).astype("int")
            return [(x, y, r) for x, y, r in circles]
        return []

    def create_bounding_boxes(self, circles: List[Tuple[int, int, int]], image_shape: Tuple[int, int]) -> Dict:
        """
        Create bounding boxes for questions and options from detected circles.
        Rows grouped by Y, then each row split into groups of 4 (A-D).
        Split to 4 columns → Q1–10, 11–20, 21–30, 31–40.
        """
        if not circles:
            return {}

        filtered = [(x, y, r) for (x, y, r) in circles if 8 <= r <= 30]
        print(f"Filtered to {len(filtered)} potential answer bubbles")
        circles_sorted = sorted(filtered, key=lambda c: (c[1], c[0]))

        rows, current_row = [], []
        row_tolerance = 35

        for x, y, r in circles_sorted:
            if not current_row or abs(y - current_row[-1][1]) <= row_tolerance:
                current_row.append((x, y, r))
            else:
                if len(current_row) >= 4:
                    srow = sorted(current_row, key=lambda c: c[0])
                    for i in range(0, len(srow), 4):
                        grp = srow[i:i+4]
                        if len(grp) == 4:
                            rows.append(grp)
                current_row = [(x, y, r)]

        if len(current_row) >= 4:
            srow = sorted(current_row, key=lambda c: c[0])
            for i in range(0, len(srow), 4):
                grp = srow[i:i+4]
                if len(grp) == 4:
                    rows.append(grp)

        print(f"Found {len(rows)} complete question rows")

        rows_with_x = [(min(row, key=lambda c: c[0])[0], row) for row in rows]
        rows_with_x.sort(key=lambda item: item[0])

        columns = [[], [], [], []]
        img_width = image_shape[1]
        col_width = max(1, img_width // 4)

        for x_pos, row in rows_with_x:
            col_idx = min(3, max(0, int(x_pos // col_width)))
            columns[col_idx].append(row)

        bounding = {}
        for col_idx, column in enumerate(columns):
            if not column:
                continue
            column_sorted = sorted(column, key=lambda row: min(row, key=lambda c: c[1])[1])
            base_q = col_idx * 10 + 1
            for row_idx, row in enumerate(column_sorted):
                qn = base_q + row_idx
                if qn > 40:
                    break
                qkey = f"Q{qn}"
                option_labels = ['A', 'B', 'C', 'D']
                options = {}
                for opt_idx, (x, y, r) in enumerate(row[:4]):
                    options[option_labels[opt_idx]] = {
                        'bbox': (x - r - 5, y - r - 5, 2*r + 10, 2*r + 10),
                        'center': (x, y),
                        'radius': r
                    }
                bounding[qkey] = options

        return bounding

    # ----------------- ANALYSIS METHODS -----------------

    def analyze_marking_traditional(self, gray: np.ndarray, bounding_boxes: Dict) -> Dict:
        results = {}
        for question, options in bounding_boxes.items():
            qres = {}
            for option, data in options.items():
                x, y, w, h = data['bbox']
                r = data['radius']
                roi = gray[y:y+h, x:x+w]
                mask = np.zeros((h, w), dtype=np.uint8)
                cv2.circle(mask, (w//2, h//2), max(1, r-2), 255, -1)
                masked_roi = cv2.bitwise_and(roi, roi, mask=mask)

                non_zero = cv2.countNonZero(mask)
                if non_zero > 0:
                    avg = float(np.sum(masked_roi)) / non_zero
                    intensity = 1.0 - (avg / 255.0)
                else:
                    intensity = 0.0

                is_marked = intensity > self.marking_threshold
                qres[option] = {
                    'marked': is_marked,
                    'confidence': intensity,
                    'intensity': intensity,
                    'threshold_status': 'high' if is_marked else 'low',
                    'cnn_prediction': False,
                    'hybrid_prediction': False
                }
            results[question] = qres
        return results

    def analyze_marking_cnn(self, gray: np.ndarray, bounding_boxes: Dict) -> Dict:
        results = {}
        for question, options in bounding_boxes.items():
            qres = {}
            for option, data in options.items():
                x, y, w, h = data['bbox']
                r = data['radius']
                roi = gray[y:y+h, x:x+w]
                mask = np.zeros((h, w), dtype=np.uint8)
                cv2.circle(mask, (w//2, h//2), max(1, r-2), 255, -1)
                masked_roi = cv2.bitwise_and(roi, roi, mask=mask)

                is_marked, confidence = self.cnn_model.predict_marking(masked_roi)

                non_zero = cv2.countNonZero(mask)
                if non_zero > 0:
                    avg = float(np.sum(masked_roi)) / non_zero
                    intensity = 1.0 - (avg / 255.0)
                else:
                    intensity = 0.0

                qres[option] = {
                    'marked': is_marked,
                    'confidence': confidence,
                    'intensity': intensity,
                    'threshold_status': 'high' if is_marked else 'low',
                    'cnn_prediction': True,
                    'hybrid_prediction': False
                }
            results[question] = qres
        return results

    def analyze_marking_hybrid(self, gray: np.ndarray, bounding_boxes: Dict) -> Dict:
        """Combine Threshold + CNN with a weighted vote (0.4 thr, 0.6 cnn)"""
        results = {}
        for question, options in bounding_boxes.items():
            qres = {}
            for option, data in options.items():
                x, y, w, h = data['bbox']
                r = data['radius']
                roi = gray[y:y+h, x:x+w]
                mask = np.zeros((h, w), dtype=np.uint8)
                cv2.circle(mask, (w//2, h//2), max(1, r-2), 255, -1)
                masked_roi = cv2.bitwise_and(roi, roi, mask=mask)

                # Threshold metrics
                non_zero = cv2.countNonZero(mask)
                if non_zero > 0:
                    avg = float(np.sum(masked_roi)) / non_zero
                    intensity = 1.0 - (avg / 255.0)
                    thr_marked = intensity > self.marking_threshold
                    thr_conf = intensity
                else:
                    intensity = 0.0
                    thr_marked = False
                    thr_conf = 0.0

                # CNN metrics
                cnn_marked, cnn_conf = self.cnn_model.predict_marking(masked_roi)

                # Combine
                if thr_marked == cnn_marked:
                    final_marked = thr_marked
                    final_conf = (thr_conf + cnn_conf) / 2.0
                    agreement = "Both"
                else:
                    combined = 0.4 * thr_conf + 0.6 * cnn_conf
                    final_marked = combined > 0.5
                    final_conf = combined
                    agreement = "CNN" if cnn_marked else "Threshold"

                qres[option] = {
                    'marked': final_marked,
                    'confidence': final_conf,
                    'intensity': intensity,
                    'threshold_status': 'high' if final_marked else 'low',
                    'threshold_marked': thr_marked,
                    'threshold_confidence': thr_conf,
                    'cnn_marked': cnn_marked,
                    'cnn_confidence': cnn_conf,
                    'agreement': agreement,
                    'hybrid_prediction': True
                }
            results[question] = qres
        return results

    def analyze_marking(self, gray: np.ndarray, bounding_boxes: Dict) -> Dict:
        if self.use_cnn and self.cnn_model and self.hybrid_mode:
            print("Using HYBRID method (Threshold + CNN combined)...")
            return self.analyze_marking_hybrid(gray, bounding_boxes)
        elif self.use_cnn and self.cnn_model:
            print("Using CNN only for bubble classification...")
            return self.analyze_marking_cnn(gray, bounding_boxes)
        else:
            print("Using traditional threshold method...")
            return self.analyze_marking_traditional(gray, bounding_boxes)

    # ----------------- VISUALIZATION & PRINTING -----------------

    def visualize_results(self, img: np.ndarray, bounding_boxes: Dict, results: Dict) -> np.ndarray:
        vis_img = img.copy()
        for question, options in bounding_boxes.items():
            for option, data in options.items():
                x, y, w, h = data['bbox']
                cx, cy = data['center']
                r = data['radius']
                if question in results and option in results[question]:
                    res = results[question][option]
                    is_marked = res['marked']
                    conf = res['confidence']
                    is_hyb = res.get('hybrid_prediction', False)
                    is_cnn = res.get('cnn_prediction', False)

                    if is_marked:
                        if is_hyb:
                            color = (0, 255, 100)
                            if res.get('agreement') != "Both":
                                color = (0, 200, 255)
                        elif is_cnn:
                            color = (0, 255, 0)
                        else:
                            color = (0, 200, 0)
                    else:
                        if is_hyb:
                            color = (0, 100, 255)
                        elif is_cnn:
                            color = (0, 0, 255)
                        else:
                            color = (0, 0, 200)

                    thickness = 3 if is_marked else 1
                    cv2.rectangle(vis_img, (x, y), (x+w, y+h), color, thickness)
                    cv2.circle(vis_img, (cx, cy), r, color, thickness)

                    method = "THR"
                    if is_hyb:
                        method = f"HYB({res.get('agreement','Both')})"
                    elif is_cnn:
                        method = "CNN"
                    label = f"{question}-{option}: {conf:.2f} ({method})"
                    cv2.putText(vis_img, label, (x, y-8),
                                cv2.FONT_HERSHEY_SIMPLEX, 0.35, color, 1)
        return vis_img

    def print_results(self, results: Dict):
        print("\n" + "="*60)
        method = "HYBRID (Threshold + CNN)" if (self.hybrid_mode and self.use_cnn) else ("CNN-ONLY" if self.use_cnn else "THRESHOLD-ONLY")
        print(f"OMR ANALYSIS RESULTS ({method}) - Organized by Batches")
        print("="*60)

        sorted_questions = sorted(results.keys(), key=lambda x: int(x[1:]) if x[1:].isdigit() else 0)

        batches = {"1-10": [], "11-20": [], "21-30": [], "31-40": []}
        for q in sorted_questions:
            qn = int(q[1:]) if q[1:].isdigit() else 0
            if 1 <= qn <= 10:
                batches["1-10"].append(q)
            elif 11 <= qn <= 20:
                batches["11-20"].append(q)
            elif 21 <= qn <= 30:
                batches["21-30"].append(q)
            elif 31 <= qn <= 40:
                batches["31-40"].append(q)

        for batch_name, questions in batches.items():
            if not questions: continue
            print(f"\n{'='*20} BATCH {batch_name} {'='*20}")
            for q in questions:
                print(f"\n{q}:")
                marked = []
                for opt, data in results[q].items():
                    status = "✓ MARKED" if data['marked'] else "✗ unmarked"
                    conf = data['confidence']
                    if data.get('hybrid_prediction', False):
                        method = f"HYB({data.get('agreement', 'Both')})"
                        if data.get('agreement') != "Both":
                            details = f" [THR:{data.get('threshold_confidence',0):.2f}, CNN:{data.get('cnn_confidence',0):.2f}]"
                        else:
                            details = ""
                    elif data.get('cnn_prediction', False):
                        method, details = "CNN", ""
                    else:
                        method, details = "THR", ""
                    print(f"  {opt}: {status} (confidence: {conf:.3f}, method: {method}){details}")
                    if data['marked']:
                        marked.append(opt)
                print(f"  → {'Answer(s): ' + ', '.join(marked) if marked else 'No answer detected'}")

    # ----------------- ANSWER SUMMARY & GRADING -----------------

    def get_answer_summary(self, results: Dict) -> Dict:
        """
        Qn -> 'A'/'B'/'C'/'D' (single), ['A','B',..] if multiple, or 'No Answer'
        """
        summary = {}
        sorted_questions = sorted(results.keys(), key=lambda x: int(x[1:]) if x[1:].isdigit() else 0)
        for question in sorted_questions:
            options = results[question]
            marked_options = [opt for opt, data in options.items() if data.get('marked', False)]
            if marked_options:
                summary[question] = marked_options[0] if len(marked_options) == 1 else marked_options
            else:
                summary[question] = "No Answer"
        return summary

    def load_answer_key(self, answer_key_input) -> Dict:
        """Load answer key from dict/list/string/file"""
        answer_key: Dict[str, str] = {}

        if isinstance(answer_key_input, dict):
            for k, v in answer_key_input.items():
                k_norm = k if k.startswith('Q') else f"Q{str(k)}"
                v_norm = str(v).strip().upper()
                if v_norm in ['A', 'B', 'C', 'D']:
                    answer_key[k_norm] = v_norm

        elif isinstance(answer_key_input, list):
            for i, ans in enumerate(answer_key_input, 1):
                a = str(ans).strip().upper()
                if a in ['A', 'B', 'C', 'D']:
                    answer_key[f"Q{i}"] = a

        elif isinstance(answer_key_input, str):
            looks_like_file = (
                len(answer_key_input) > 50 or
                '/' in answer_key_input or '\\' in answer_key_input or
                answer_key_input.lower().endswith('.txt')
            )
            if looks_like_file:
                try:
                    with open(answer_key_input, 'r') as f:
                        content = f.read().strip()
                    if '=' in content or ':' in content:
                        for line in content.splitlines():
                            line = line.strip()
                            if not line:
                                continue
                            if '=' in line:
                                q, a = line.split('=', 1)
                            elif ':' in line:
                                q, a = line.split(':', 1)
                            else:
                                continue
                            q = q.strip()
                            a = a.strip().upper()
                            if not q.startswith('Q'):
                                q = f"Q{q}"
                            if a in ['A', 'B', 'C', 'D']:
                                answer_key[q] = a
                    else:
                        for i, ch in enumerate(content, 1):
                            c = ch.upper()
                            if c in ['A', 'B', 'C', 'D']:
                                answer_key[f"Q{i}"] = c
                except FileNotFoundError:
                    print(f"Warning: Answer key file '{answer_key_input}' not found. Treating as answer string.")
                    for i, ch in enumerate(answer_key_input, 1):
                        c = ch.upper()
                        if c in ['A', 'B', 'C', 'D']:
                            answer_key[f"Q{i}"] = c
            else:
                for i, ch in enumerate(answer_key_input, 1):
                    c = ch.upper()
                    if c in ['A', 'B', 'C', 'D']:
                        answer_key[f"Q{i}"] = c

        return answer_key

    def compare_with_answer_key(self, student_answers: Dict, answer_key: Dict) -> Dict:
        comparison = {
            'correct': [],
            'incorrect': [],
            'unanswered': [],
            'multiple_marked': [],
            'score': 0,
            'total_questions': 0,
            'percentage': 0.0,
            'detailed_results': {}
        }

        all_questions = set(student_answers.keys()) | set(answer_key.keys())
        comparison['total_questions'] = len(all_questions)

        for question in sorted(all_questions, key=lambda x: int(x[1:]) if x[1:].isdigit() else 0):
            student_answer = student_answers.get(question, "No Answer")
            correct_answer = answer_key.get(question, "Unknown")

            result = {
                'student_answer': student_answer,
                'correct_answer': correct_answer,
                'status': '',
                'points': 0
            }

            if isinstance(student_answer, list):
                result['status'] = 'Multiple Marked'
                comparison['multiple_marked'].append(question)
            elif student_answer == "No Answer":
                result['status'] = 'Unanswered'
                comparison['unanswered'].append(question)
            elif correct_answer == "Unknown":
                result['status'] = 'No Answer Key'
            elif student_answer == correct_answer:
                result['status'] = 'Correct'
                result['points'] = 1
                comparison['correct'].append(question)
                comparison['score'] += 1
            else:
                result['status'] = 'Incorrect'
                comparison['incorrect'].append(question)

            comparison['detailed_results'][question] = result

        if comparison['total_questions'] > 0:
            comparison['percentage'] = (comparison['score'] / comparison['total_questions']) * 100.0

        return comparison

    def print_comparison_results(self, comparison: Dict, show_detailed: bool = True):
        print("\n" + "="*80)
        method_name = "HYBRID (Threshold + CNN)" if (self.hybrid_mode and self.use_cnn) else ("CNN-ONLY" if self.use_cnn else "THRESHOLD-ONLY")
        print(f"OMR GRADING RESULTS - {method_name}")
        print("="*80)

        print(f"\nSCORE: {comparison['score']}/{comparison['total_questions']} ({comparison['percentage']:.1f}%)")
        print(f"Correct: {len(comparison['correct'])}")
        print(f"Incorrect: {len(comparison['incorrect'])}")
        print(f"Unanswered: {len(comparison['unanswered'])}")
        print(f"Multiple Marked: {len(comparison['multiple_marked'])}")

        p = comparison['percentage']
        if p >= 90: grade = "A+"
        elif p >= 85: grade = "A"
        elif p >= 80: grade = "A-"
        elif p >= 75: grade = "B+"
        elif p >= 70: grade = "B"
        elif p >= 65: grade = "B-"
        elif p >= 60: grade = "C+"
        elif p >= 55: grade = "C"
        elif p >= 50: grade = "C-"
        else: grade = "F"
        print(f"\nESTIMATED GRADE: {grade}")

        if show_detailed:
            print("\n" + "="*50)
            print("DETAILED RESULTS BY BATCH")
            print("="*50)

            batches = {"1-10": [], "11-20": [], "21-30": [], "31-40": []}
            for q in sorted(comparison['detailed_results'].keys(), key=lambda x: int(x[1:]) if x[1:].isdigit() else 0):
                qn = int(q[1:]) if q[1:].isdigit() else 0
                if 1 <= qn <= 10: batches["1-10"].append(q)
                elif 11 <= qn <= 20: batches["11-20"].append(q)
                elif 21 <= qn <= 30: batches["21-30"].append(q)
                elif 31 <= qn <= 40: batches["31-40"].append(q)

            for batch_name, questions in batches.items():
                if not questions: continue
                print(f"\n{'='*15} BATCH {batch_name} {'='*15}")
                batch_correct = 0
                for q in questions:
                    res = comparison['detailed_results'][q]
                    sym = {'Correct':'✓','Incorrect':'✗','Unanswered':'○','Multiple Marked':'◐','No Answer Key':'?'}\
                          .get(res['status'], '?')
                    print(f"{q}: {str(res['student_answer']):>12} | Correct: {str(res['correct_answer']):>2} | {sym} {res['status']}")
                    if res['status'] == 'Correct':
                        batch_correct += 1
                batch_total = len(questions)
                bperc = (batch_correct / batch_total) * 100 if batch_total else 0.0
                print(f"Batch Score: {batch_correct}/{batch_total} ({bperc:.1f}%)")

        if comparison['incorrect']:
            print(f"\nINCORRECT ANSWERS: {', '.join(comparison['incorrect'])}")
        if comparison['unanswered']:
            print(f"UNANSWERED: {', '.join(comparison['unanswered'])}")
        if comparison['multiple_marked']:
            print(f"MULTIPLE MARKED: {', '.join(comparison['multiple_marked'])}")

    def save_grading_report(self, comparison: Dict, student_answers: Dict, filename: str = "grading_report.txt"):
        with open(filename, 'w') as f:
            method_name = "HYBRID (Threshold + CNN)" if (self.hybrid_mode and self.use_cnn) else ("CNN-ONLY" if self.use_cnn else "THRESHOLD-ONLY")
            f.write(f"OMR GRADING REPORT - {method_name}\n")
            f.write("="*50 + "\n\n")
            f.write(f"Score: {comparison['score']}/{comparison['total_questions']} ({comparison['percentage']:.1f}%)\n")
            f.write(f"Correct: {len(comparison['correct'])}\n")
            f.write(f"Incorrect: {len(comparison['incorrect'])}\n")
            f.write(f"Unanswered: {len(comparison['unanswered'])}\n")
            f.write(f"Multiple Marked: {len(comparison['multiple_marked'])}\n\n")
            f.write("DETAILED RESULTS:\n")
            f.write("-"*30 + "\n")
            for q in sorted(comparison['detailed_results'].keys(), key=lambda x: int(x[1:]) if x[1:].isdigit() else 0):
                res = comparison['detailed_results'][q]
                f.write(f"{q}: Student={res['student_answer']}, Correct={res['correct_answer']}, Status={res['status']}\n")
        print(f"\nDetailed grading report saved as '{filename}'")

    # ----------------- Evaluation plots for A–D grading -----------------

    def plot_grading_confusion_matrix(self, comparison: Dict, save_path="grading_cm.png"):
        """
        Confusion matrix for question-level predictions (A–D).
        Includes only questions with a single predicted option and known correct option.
        """
        labels = ["A", "B", "C", "D"]
        y_true, y_pred = [], []

        for q, res in comparison.get("detailed_results", {}).items():
            ca = res.get("correct_answer")
            sa = res.get("student_answer")
            if isinstance(sa, str) and sa in labels and ca in labels:
                y_true.append(ca)
                y_pred.append(sa)

        if not y_true:
            print("No comparable questions to plot a grading confusion matrix.")
            return

        cm = confusion_matrix(y_true, y_pred, labels=labels)
        fig, ax = plt.subplots()
        disp = ConfusionMatrixDisplay(cm, display_labels=labels)
        disp.plot(ax=ax, colorbar=False)
        ax.set_title("Grading Confusion Matrix (A–D)")
        plt.tight_layout()
        plt.savefig(save_path, dpi=200)
        print(f"Saved: {save_path}")

    def plot_grading_roc_auc(self, results: Dict, answer_key: Dict, save_prefix="grading"):
        """
        One-vs-rest ROC & AUC for A–D using per-option 'confidence' scores from results.
        """
        labels = ["A", "B", "C", "D"]
        label_to_idx = {l: i for i, l in enumerate(labels)}

        y_true_idx = []
        y_scores = []

        for q, opts in results.items():
            ca = answer_key.get(q)
            if ca not in labels:
                continue

            # Collect scores in A,B,C,D order
            scores = []
            ok = True
            for l in labels:
                d = opts.get(l, {})
                if "confidence" not in d:
                    ok = False
                    break
                scores.append(float(d["confidence"]))
            if not ok:
                continue

            y_true_idx.append(label_to_idx[ca])
            y_scores.append(scores)

        if not y_scores:
            print("No scores available to compute grading ROC/AUC.")
            return

        y_scores = np.asarray(y_scores)                     # (N, 4)
        y_true_bin = label_binarize(y_true_idx, classes=[0, 1, 2, 3])  # (N, 4)

        fpr, tpr, roc_auc = {}, {}, {}
        for i, l in enumerate(labels):
            fpr[i], tpr[i], _ = roc_curve(y_true_bin[:, i], y_scores[:, i])
            roc_auc[i] = auc(fpr[i], tpr[i])

        macro_auc = float(np.mean([roc_auc[i] for i in range(4)]))

        plt.figure()
        for i, l in enumerate(labels):
            plt.plot(fpr[i], tpr[i], label=f"{l} (AUC={roc_auc[i]:.3f})")
        plt.plot([0, 1], [0, 1], "--")
        plt.xlabel("False Positive Rate")
        plt.ylabel("True Positive Rate")
        plt.title(f"Grading ROC (One-vs-Rest) • Macro AUC={macro_auc:.3f}")
        plt.legend(loc="lower right")
        plt.tight_layout()
        out_path = f"{save_prefix}_roc.png"
        plt.savefig(out_path, dpi=200)
        print(f"Saved: {out_path}")
        print("Per-class AUC:", {labels[i]: round(roc_auc[i], 4) for i in range(4)})
        print(f"Macro-average AUC: {macro_auc:.4f}")

    # ----------------- PIPELINE -----------------

    def process_omr_sheet(self, image_path: str) -> Tuple[Dict, Dict, np.ndarray]:
        img, gray, thresh = self.preprocess_image(image_path)
        circles = self.find_circles(gray)
        print(f"Detected {len(circles)} circles")
        bounding_boxes = self.create_bounding_boxes(circles, gray.shape)
        print(f"Created bounding boxes for {len(bounding_boxes)} questions")
        results = self.analyze_marking(gray, bounding_boxes)
        vis_img = self.visualize_results(img, bounding_boxes, results)
        return bounding_boxes, results, vis_img

    def process_omr_with_grading(self, image_path: str, answer_key_input) -> Tuple[Dict, Dict, Dict, np.ndarray]:
        bounding_boxes, results, vis_img = self.process_omr_sheet(image_path)
        student_answers = self.get_answer_summary(results)
        answer_key = self.load_answer_key(answer_key_input)
        comparison = self.compare_with_answer_key(student_answers, answer_key)
        return bounding_boxes, results, comparison, vis_img


# ----------------------------- Main runner -----------------------------

def main():
    # Initialize detector with hybrid mode (threshold + CNN)
    detector = OMRDetector(use_cnn=True, hybrid_mode=True)
    detector.marking_threshold = 0.30  # tweak as needed

    # ----- Inputs -----
    image_path = "C:/Users/Hakeema Rizan/mlops_lab/OMR/ans sheet/IMG-20250803-WA0015.jpg"  # <-- change to your image path
    answer_key = {
        "Q1": "B", "Q2": "B", "Q3": "B", "Q4": "A", "Q5": "D",
        "Q6": "D", "Q7": "C", "Q8": "C", "Q9": "B", "Q10": "B",
        "Q11": "A", "Q12": "D", "Q13": "B", "Q14": "C", "Q15": "A",
        "Q16": "C", "Q17": "D", "Q18": "D", "Q19": "C", "Q20": "D",
        "Q21": "A", "Q22": "D", "Q23": "A", "Q24": "D", "Q25": "A",
        "Q26": "D", "Q27": "B", "Q28": "C", "Q29": "C", "Q30": "A",
        "Q31": "B", "Q32": "D", "Q33": "A", "Q34": "D", "Q35": "A",
        "Q36": "C", "Q37": "D", "Q38": "C", "Q39": "B", "Q40": "D"
    }

    try:
        # Process OMR & grade
        bounding_boxes, results, comparison, visualization = detector.process_omr_with_grading(image_path, answer_key)

        # Detected answers (summary)
        print("\n" + "="*40)
        print("DETECTED ANSWERS")
        print("="*40)
        summary = detector.get_answer_summary(results)
        for question, answer in summary.items():
            print(f"{question}: {answer}")

        # Detailed analysis
        detector.print_results(results)

        # Grading summary
        detector.print_comparison_results(comparison, show_detailed=True)

        # Save artifacts
        detector.save_grading_report(comparison, summary, "hybrid_grading_report.txt")
        cv2.imwrite("omr_hybrid_results.jpg", visualization)
        print(f"\nVisualization saved as 'omr_hybrid_results.jpg'")

        # Hybrid agreement stats
        if detector.hybrid_mode and detector.use_cnn:
            print("\n" + "="*50)
            print("HYBRID METHOD AGREEMENT ANALYSIS")
            print("="*50)
            stats = {"Both": 0, "CNN": 0, "Threshold": 0}
            total = 0
            for _, options in results.items():
                for _, data in options.items():
                    if data.get('hybrid_prediction', False):
                        stats[data.get('agreement', 'Both')] += 1
                        total += 1
            if total > 0:
                print(f"Total bubbles analyzed: {total}")
                print(f"Both methods agreed: {stats['Both']} ({stats['Both']/total*100:.1f}%)")
                print(f"CNN override: {stats['CNN']} ({stats['CNN']/total*100:.1f}%)")
                print(f"Threshold override: {stats['Threshold']} ({stats['Threshold']/total*100:.1f}%)")

        # --- CNN curves + confusion matrix + ROC/AUC
        if detector.use_cnn and detector.cnn_model is not None:
            detector.cnn_model.plot_training_curves(save_prefix="cnn_training")
            detector.cnn_model.plot_cnn_confusion_roc_auc(normalize="true", save_prefix="cnn_eval")

        # --- Grading confusion matrix + ROC/AUC (A–D, one-vs-rest)
        detector.plot_grading_confusion_matrix(comparison, save_path="grading_cm.png")
        detector.plot_grading_roc_auc(results, answer_key, save_prefix="grading")

        print("\nSaved files:")
        print("- omr_hybrid_results.jpg")
        print("- hybrid_grading_report.txt")
        print("- cnn_training_accuracy.png, cnn_training_loss.png (now include TEST curves)")
        print("- cnn_eval_cm.png, cnn_eval_roc.png")
        print("- grading_cm.png, grading_roc.png")

    except Exception as e:
        print(f"Error processing OMR sheet: {e}")
        print("Please check:")
        print("1) Image path is correct & readable")
        print("2) Image contains clear circular answer bubbles")
        print("3) Answer key format is correct")
        print("4) Dependencies installed: opencv-python, tensorflow, matplotlib, scikit-learn, numpy")


if __name__ == "__main__":
    main()